// Package config loads the Archangel backend's configuration: where to bind,
// where the auth token hash lives, and other server-wide settings.
package config

import (
	"fmt"
	"os"

	"gopkg.in/yaml.v3"
)

type Config struct {
	// BindAddr MUST be the WireGuard interface IP (e.g. "10.10.0.1"), never
	// "0.0.0.0" or a public IP. This is what keeps the API unreachable from
	// the public internet - the single most important setting in this file.
	// UFW closing the port publicly is the second layer; this is the first.
	BindAddr string `yaml:"bind_addr"`
	Port     int    `yaml:"port"`

	// TokenHash is the SHA-256 hash (hex-encoded) of the auth token, never
	// the plaintext token itself. Generated by `archangeld gen-token`.
	TokenHash string `yaml:"token_hash"`

	// FilesRoot is the directory the file browser is jailed to (Milestone 2).
	FilesRoot string `yaml:"files_root"`
}

func Load(path string) (*Config, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, fmt.Errorf("reading config %s: %w", path, err)
	}

	var cfg Config
	if err := yaml.Unmarshal(data, &cfg); err != nil {
		return nil, fmt.Errorf("parsing config %s: %w", path, err)
	}

	if cfg.BindAddr == "" || cfg.BindAddr == "0.0.0.0" {
		return nil, fmt.Errorf("bind_addr must be set to the WireGuard interface IP, not empty or 0.0.0.0 (got %q)", cfg.BindAddr)
	}
	if cfg.Port == 0 {
		cfg.Port = 8443
	}
	if cfg.TokenHash == "" {
		return nil, fmt.Errorf("token_hash is not set - run `archangeld gen-token` first")
	}

	return &cfg, nil
}

func (c *Config) Addr() string {
	return fmt.Sprintf("%s:%d", c.BindAddr, c.Port)
}
